[package]
name = "unicycle"
version = "0.3.4"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/udoprog/unicycle"
homepage = "https://github.com/udoprog/unicycle"
documentation = "https://docs.rs/unicycle"
description = """
A scheduler for driving a large number of futures.
"""
keywords = ["async", "futures", "future"]
categories = ["asynchronous", "algorithms"]

[features]
default = ["vec-safety"]
parking-lot = ["lock_api", "parking_lot"]
vec-safety = []
test-op-count = []

[dependencies]
futures-core = "0.3.1"
parking_lot = {version = "0.10.0", optional = true}
lock_api = {version = "0.3.3", optional = true}

[dev-dependencies]
tokio = {version = "0.2.10", features = ["full"]}
checkers = "0.5.6"
rand = "0.7.3"
futures = "0.3.1"
pin-utils = "0.1.0-alpha.4"
hibitset = "0.6.2"
criterion = "0.3"
crossbeam = "0.7.3"

[[bench]]
name = "bitset"
harness = false

[[bench]]
name = "unordered"
harness = false