[package]
name = "unicycle"
version = "0.1.1"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/udoprog/checkers"
homepage = "https://github.com/udoprog/checkers"
documentation = "https://docs.rs/checkers"
description = """
A scheduler for driving a large number of futures.
"""
keywords = ["async", "futures", "future"]
categories = ["asynchronous", "algorithms"]

[dependencies]
futures-core = "0.3.1"
parking_lot = "0.10.0"
lock_api = "0.3.3"

[dev-dependencies]
tokio = {version = "0.2.10", features = ["full"]}
checkers = "0.5.6"
rand = "0.7.3"
futures = "0.3.1"
pin-utils = "0.1.0-alpha.4"